name: hello world
inputs:
  your-name:
    description: "Your name to say hello"
    required: true
    default: "world"
outputs:
  message:
    description: "Welcome message for you"
    value: "Hello ${{ inputs.your-name }}, how are you"
runs:
 - run: echo "Custom github action"
   shell: bash 