name: Execute resuable workflow
on:
  workflow_dispatch
jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      username: Vinit
    secrets:
      envPAT: envPATValue
