name: Execute resuable workflow
on:
  workflow_dispatch
jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      username: Vinit
    secrets:
      envPAT: envPATValue
  print_outputs:
    runs-on: ubuntu-latest
    needs: call_reusable_workflow
    steps:
      - run: echo Output from resuable workflow
      - run: echo ${{ needs.call_reusable_workflow.outputs.firstWord }} ${{ needs.call_reusable_workflow.outputs.secondWord }}