name: Reusable workflow
on: 
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
jobs:
  resuable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      run: echo username is ${{ inputs.username }}
      run: echo envPAT is ${{ secrets.envPAT }}